# Generated by Django 4.1 on 2022-08-25 03:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0006_alter_entry_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entry",
            name="author",
            field=models.OneToOneField(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="entry",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
