# Generated by Django 4.1 on 2022-08-25 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_entry_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entry",
            name="interests",
            field=models.TextField(
                default="", help_text="Statement of general project interests"
            ),
        ),
        migrations.AlterField(
            model_name="entry",
            name="project_description",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="entry",
            name="project_name",
            field=models.CharField(default="", max_length=100),
        ),
    ]
