# Generated by Django 4.1 on 2022-08-26 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_emaillog"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="emaillog",
            name="email",
        ),
    ]
