# Generated by Django 4.1 on 2022-08-26 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_remove_emaillog_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="emaillog",
            name="email_type",
            field=models.CharField(default="overdue", max_length=100),
            preserve_default=False,
        ),
    ]
